/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minesweeperframe;

/**
 *
 * @author l154011
 */
public class MinesweeperFrame extends javax.swing.JFrame {

    /**
     * Creates new form MinesweeperFrame
     */
    public MinesweeperFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GameBoard = new javax.swing.JPanel();
        b0 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        b26 = new javax.swing.JButton();
        b27 = new javax.swing.JButton();
        b28 = new javax.swing.JButton();
        b29 = new javax.swing.JButton();
        b30 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();
        b32 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();
        b34 = new javax.swing.JButton();
        b35 = new javax.swing.JButton();
        b36 = new javax.swing.JButton();
        b37 = new javax.swing.JButton();
        b38 = new javax.swing.JButton();
        b39 = new javax.swing.JButton();
        b40 = new javax.swing.JButton();
        b41 = new javax.swing.JButton();
        b42 = new javax.swing.JButton();
        b43 = new javax.swing.JButton();
        b44 = new javax.swing.JButton();
        b45 = new javax.swing.JButton();
        b46 = new javax.swing.JButton();
        b47 = new javax.swing.JButton();
        b48 = new javax.swing.JButton();
        b49 = new javax.swing.JButton();
        b50 = new javax.swing.JButton();
        b51 = new javax.swing.JButton();
        b52 = new javax.swing.JButton();
        b53 = new javax.swing.JButton();
        b54 = new javax.swing.JButton();
        b55 = new javax.swing.JButton();
        b56 = new javax.swing.JButton();
        b57 = new javax.swing.JButton();
        b58 = new javax.swing.JButton();
        b59 = new javax.swing.JButton();
        b60 = new javax.swing.JButton();
        b61 = new javax.swing.JButton();
        b62 = new javax.swing.JButton();
        b63 = new javax.swing.JButton();
        b64 = new javax.swing.JButton();
        b65 = new javax.swing.JButton();
        b66 = new javax.swing.JButton();
        b67 = new javax.swing.JButton();
        b68 = new javax.swing.JButton();
        b69 = new javax.swing.JButton();
        b70 = new javax.swing.JButton();
        b71 = new javax.swing.JButton();
        b72 = new javax.swing.JButton();
        b73 = new javax.swing.JButton();
        b74 = new javax.swing.JButton();
        b75 = new javax.swing.JButton();
        b76 = new javax.swing.JButton();
        b77 = new javax.swing.JButton();
        b78 = new javax.swing.JButton();
        b79 = new javax.swing.JButton();
        b80 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GameBoard.setBackground(new java.awt.Color(0, 102, 204));
        GameBoard.setLayout(new java.awt.GridLayout(9, 9));

        b0.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b0);

        b1.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b1);

        b2.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b2);

        b3.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b3);

        b4.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b4);

        b5.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b5);

        b6.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b6);

        b7.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b7);

        b8.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b8);

        b9.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b9);

        b10.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b10);

        b11.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b11);

        b12.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b12);

        b13.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b13);

        b14.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b14);

        b15.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b15);

        b16.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b16);

        b17.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b17);

        b18.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b18);

        b19.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b19);

        b20.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b20);

        b21.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b21);

        b22.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b22);

        b23.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b23);

        b24.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b24);

        b25.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b25);

        b26.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b26);

        b27.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b27);

        b28.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b28);

        b29.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b29);

        b30.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b30);

        b31.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b31);

        b32.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b32);

        b33.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b33);

        b34.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b34);

        b35.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b35);

        b36.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b36);

        b37.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b37);

        b38.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b38);

        b39.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b39);

        b40.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b40);

        b41.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b41);

        b42.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b42);

        b43.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b43);

        b44.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b44);

        b45.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b45);

        b46.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b46);

        b47.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b47);

        b48.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b48);

        b49.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b49);

        b50.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b50);

        b51.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b51);

        b52.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b52);

        b53.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b53);

        b54.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b54);

        b55.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b55);

        b56.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b56);

        b57.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b57);

        b58.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b58);

        b59.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b59);

        b60.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b60);

        b61.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b61);

        b62.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b62);

        b63.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b63);

        b64.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b64);

        b65.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b65);

        b66.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b66);

        b67.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b67);

        b68.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b68);

        b69.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b69);

        b70.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b70);

        b71.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b71);

        b72.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b72);

        b73.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b73);

        b74.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b74);

        b75.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b75);

        b76.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b76);

        b77.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b77);

        b78.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b78);

        b79.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b79);

        b80.setBackground(new java.awt.Color(0, 153, 255));
        GameBoard.add(b80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(GameBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(GameBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinesweeperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinesweeperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinesweeperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinesweeperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinesweeperFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GameBoard;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b2;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b25;
    private javax.swing.JButton b26;
    private javax.swing.JButton b27;
    private javax.swing.JButton b28;
    private javax.swing.JButton b29;
    private javax.swing.JButton b3;
    private javax.swing.JButton b30;
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton b34;
    private javax.swing.JButton b35;
    private javax.swing.JButton b36;
    private javax.swing.JButton b37;
    private javax.swing.JButton b38;
    private javax.swing.JButton b39;
    private javax.swing.JButton b4;
    private javax.swing.JButton b40;
    private javax.swing.JButton b41;
    private javax.swing.JButton b42;
    private javax.swing.JButton b43;
    private javax.swing.JButton b44;
    private javax.swing.JButton b45;
    private javax.swing.JButton b46;
    private javax.swing.JButton b47;
    private javax.swing.JButton b48;
    private javax.swing.JButton b49;
    private javax.swing.JButton b5;
    private javax.swing.JButton b50;
    private javax.swing.JButton b51;
    private javax.swing.JButton b52;
    private javax.swing.JButton b53;
    private javax.swing.JButton b54;
    private javax.swing.JButton b55;
    private javax.swing.JButton b56;
    private javax.swing.JButton b57;
    private javax.swing.JButton b58;
    private javax.swing.JButton b59;
    private javax.swing.JButton b6;
    private javax.swing.JButton b60;
    private javax.swing.JButton b61;
    private javax.swing.JButton b62;
    private javax.swing.JButton b63;
    private javax.swing.JButton b64;
    private javax.swing.JButton b65;
    private javax.swing.JButton b66;
    private javax.swing.JButton b67;
    private javax.swing.JButton b68;
    private javax.swing.JButton b69;
    private javax.swing.JButton b7;
    private javax.swing.JButton b70;
    private javax.swing.JButton b71;
    private javax.swing.JButton b72;
    private javax.swing.JButton b73;
    private javax.swing.JButton b74;
    private javax.swing.JButton b75;
    private javax.swing.JButton b76;
    private javax.swing.JButton b77;
    private javax.swing.JButton b78;
    private javax.swing.JButton b79;
    private javax.swing.JButton b8;
    private javax.swing.JButton b80;
    private javax.swing.JButton b9;
    // End of variables declaration//GEN-END:variables
}
